day_10_django/test4/booktest/urls.py
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path("", views.index, name='index'),
    path("show", views.show, name='show'),
    re_path(r"^(\d+)$", views.show_re, name='show_re'),

    path("index2", views.index2, name='index2'),
    path("user1", views.user1, name='user1'),
    path("user2", views.user2, name='user2'),
    path("htmlTest", views.htmlTest, name='htmlTest'),

    path("csrf1", views.csrf1, name='csrf1'),
    path("csrf2", views.csrf2, name='csrf2'),
]

day_10_django/test4/test4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('booktest/', include(('booktest.urls', 'booktest'), namespace='booktest'))
]

day_10_django/test4/booktest/models.py
from django.db import models


class BookInfoManager(models.Manager):
    def get_queryset(self):
        return super(BookInfoManager, self).get_queryset().filter(isDeleted=False)

    # 创建 bookInfo对象 方法2
    def create(self, title, pub_date):
        b = BookInfo()
        b.btitle = title
        b.bpub_date = pub_date
        b.bread = 0
        b.bcommet = 0
        b.isDeleted = False
        return b


class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_date = models.DateTimeField(db_column='pub_date')
    bread = models.IntegerField(default=0)
    bcommet = models.IntegerField(null=False)
    isDeleted = models.BooleanField(default=False)

    class Meta:
        db_table = 'bookinfo'

    books1 = models.Manager()
    books2 = BookInfoManager()

    # 创建 bookInfo对象 方法1
    @classmethod
    def create(cls, title, pub_date):
        b = cls(btitle=title, bpub_date=pub_date)
        b.bread = 0
        b.bcommet = 0
        b.isDeleted = False
        return b


class HeroInfo(models.Model):
    hname = models.CharField(max_length=10)
    hgender = models.BooleanField(default=True)
    hcontent = models.CharField(max_length=1000)
    isDeleted = models.BooleanField(default=False)
    book = models.ForeignKey(BookInfo, on_delete=models.CASCADE)

    def showname(self):
        return self.hname

day_10_django/test4/booktest/views.py
from django.shortcuts import render
from .models import *
from django.http import HttpResponse


# Create your views here.
def index(request):
    hero = HeroInfo.objects.get(pk=1)
    list = HeroInfo.objects.all()
    context = {"hero": hero, 'list': list}
    return render(request, 'booktest/index.html', context)


def show(request, id=None):
    context = {'id': id}
    return render(request, 'booktest/show.html', context)


def show_re(request, id):
    context = {'id': id}
    return render(request, 'booktest/show.html', context)


def index2(request):
    context = {}
    return render(request, 'booktest/index2.html', context)


def user1(request):
    context = {'username': '张大胆'}
    return render(request, 'booktest/user1.html', context)


def user2(request):
    context = {}
    return render(request, 'booktest/user2.html', context)


# html转义
def htmlTest(request):
    context = {'t1': '<h1>h1</h1>'}
    return render(request, 'booktest/htmlTest.html', context)


# csrf 跨站
def csrf1(request):
    context = {}
    return render(request, 'booktest/csrf1.html', context)


def csrf2(request):
    username_ = request.POST['username']
    return HttpResponse(username_)

day_10_django/test4/templates/booktest/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
    {% block head %}
    {% endblock %}
</head>
<body>
<h1>logo</h1>
<hr>
{% block content1 %}
<h1>abc</h1>
{% endblock %}
<hr>
<h1>contact</h1>
</body>
</html>

day_10_django/test4/templates/booktest/base_goods.html
{% extends './base.html' %}

day_10_django/test4/templates/booktest/base_user.html
{% extends './base.html' %}

{% block content1 %}
<table border="1">
    <tr>
        <td height="300">用户<br>导航</td>
        <td>{% block user_content%}{% endblock %}</td>
    </tr>
</table>
{% endblock %}

day_10_django/test4/templates/booktest/csrf1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="/booktest/csrf2" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="username">
    <input type="submit" value="submit">
</form>
</body>
</html>

day_10_django/test4/templates/booktest/htmlTest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{t1}}
<hr>
{{t1|safe}}
<hr>
{% autoescape off %}
{{t1}}
{% endautoescape %}
<hr>
字面值：<br>
{{t2|default:'<h1>abc</h1>'}}<br>
手动转义：
{{t2|default:'&lt;h1&gt;abc&lt;/h1&gt;'}}
</body>
</html>

day_10_django/test4/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
{{hero.showname}}
<hr>
<a href="/booktest/11111">来吧，展示----1</a> <br>
<a href="{% url 'booktest:show'  %}">来吧，展示----2</a> <br>
<a href="{% url 'booktest:show_re' 123 %}">来吧，展示----3</a> <br>
<hr>
奇数行显示红色，偶数行显示蓝色
<br/>
<ul>
    {% for hero in list %}
    {% if forloop.counter|divisibleby:2 %}
    <li style="color: red">{{forloop.counter}}:{{hero.showname}}</li>
    {% else %}
    <li style="color: blue">{{forloop.counter}}:{{hero.showname}}</li>
    {% endif %}
    {% empty %}
    <li>啥也没找到</li>
    {% endfor %}
</ul>

</body>
</html>

day_10_django/test4/templates/booktest/index2.html
{% extends './base.html' %}

{% block content1 %}
<h1>123 </h1>
{% endblock%}

day_10_django/test4/templates/booktest/show.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>
{{id}}
</body>
</html>

day_10_django/test4/templates/booktest/user1.html
{% extends './base_user.html' %}

{% block head %}
<script>alert("hello")</script>
{% endblock %}

{% block user_content %}
<h1>用户中心1</h1>
用户名：{{username}}
{% endblock user_content %}

day_10_django/test4/templates/booktest/user2.html
{% extends './base_user.html' %}

{% block user_content %}
<h1>用户中心2</h1>
{% endblock user_content %}